### ISSUE TITLE
The models trained on 128x128 dataset

### ISSUE THREAD

**Issue by o0t1ng0o** [zhixinshu/DeformingAutoencoders-pytorch#6]
Hi, @zhixinshu 
I want to train the model with 128x128 input on CelebA dataset.
Thus, i add additional layers in both encoder and decoder.
The codes are as follows:
```
class waspDenseEncoder(nn.Module):
    def __init__(self, opt, ngpu=1, nc=1, ndf = 32, ndim = 128, activation=nn.LeakyReLU, args=[0.2, False], f_activation=nn.Sigmoid, f_args=[]):
        super(waspDenseEncoder, self).__init__()
        self.ngpu = ngpu
        self.ndim = ndim

        self.main = nn.Sequential(
                # input is (nc) x 128 x 128
                nn.BatchNorm2d(nc),
                nn.ReLU(True),
                nn.Conv2d(nc, ndf, 4, stride=2, padding=1),

                # state size. (ndf) x 64 x 64
                DenseBlockEncoder(ndf, 6),
                DenseTransitionBlockEncoder(ndf, ndf*2, 2, activation=activation, args=args),

                # state size. (ndf*2) x 32 x 32
                DenseBlockEncoder(ndf*2, 12),
                DenseTransitionBlockEncoder(ndf*2, ndf*4, 2, activation=activation, args=args),

                # state size. (ndf*4) x 16 x 16
                DenseBlockEncoder(ndf*4, 24),
                DenseTransitionBlockEncoder(ndf*4, ndf*8, 2, activation=activation, args=args),

                # state size. (ndf*8) x 8 x 8
                DenseBlockEncoder(ndf*8, 24),
                DenseTransitionBlockEncoder(ndf*8, ndf*16, 2, activation=activation, args=args),
                
                # state size. (ndf*16) x 4 x 4
                DenseBlockEncoder(ndf*16, 16),
                DenseTransitionBlockEncoder(ndf*16, ndim, 4, activation=activation, args=args),
                f_activation(*f_args),
        )

    def forward(self, input):
        output = self.main(input).view(-1,self.ndim)
        return output   

class waspDenseDecoder(nn.Module):
    def __init__(self, opt, ngpu=1, nz=128, nc=1, ngf=32, lb=0, ub=1, activation=nn.ReLU, args=[False], f_activation=nn.Hardtanh, f_args=[0,1]):
        super(waspDenseDecoder, self).__init__()
        self.ngpu   = ngpu
        self.main   = nn.Sequential(
            # input is Z, going into convolution
            nn.BatchNorm2d(nz),
            activation(*args),
            nn.ConvTranspose2d(nz, ngf * 16, 4, 1, 0, bias=False),

            # state size. (ngf*16) x 4 x 4
            DenseBlockDecoder(ngf*16, 16),
            DenseTransitionBlockDecoder(ngf*16, ngf*8),
            
            # state size. (ngf*8) x 8 x 8
            DenseBlockDecoder(ngf*8, 24),
            DenseTransitionBlockDecoder(ngf*8, ngf*4),

            # state size. (ngf*4) x 16 x 16
            DenseBlockDecoder(ngf*4, 24),
            DenseTransitionBlockDecoder(ngf*4, ngf*2),

            # state size. (ngf*2) x 32 x 32
            DenseBlockDecoder(ngf*2, 12),
            DenseTransitionBlockDecoder(ngf*2, ngf),

            # state size. (ngf) x 64 x 64
            DenseBlockDecoder(ngf, 6),
            DenseTransitionBlockDecoder(ngf, ngf),

            # state size (ngf) x 128 x 128
            nn.BatchNorm2d(ngf),
            activation(*args),
            nn.ConvTranspose2d(ngf, nc, 3, stride=1, padding=1, bias=False),
            f_activation(*f_args),
        )
    def forward(self, inputs):
        return self.main(inputs)
```
Although the training processing is normal, the texture is wired.
Texture：
![iter_225200_tex0_](https://user-images.githubusercontent.com/16815652/49355607-5b170d00-f703-11e8-827f-31805ef397e0.png)
Output：
![iter_225200_output0_](https://user-images.githubusercontent.com/16815652/49355632-6c601980-f703-11e8-8a06-e980aa4a2f4a.png)

Could you give me some advice for training 128x128 size image?
Many thanks!

**Comment by o0t1ng0o** [comment]
Additionally, these are the loss diagrams.
![loss](https://user-images.githubusercontent.com/16815652/49355837-4dae5280-f704-11e8-952f-6efa2e30c6ac.png)

**Comment by zhixinshu** [comment]
Hi, it seems the texture has been placed in the top left from the results. If you visualize the deformation grid it probably is only sampling from part of the texture canvas. It seems the sampling grids are within the [-1,0] interval on both x and y axes, instead of [-1,1].

A possible problem is that since the image size is also a parameter of the model, it should be changed to 128 (it was hard coded in line 46 in train_DAE_CelebA: opt.imgSize=64); 

If you have already done the previous part, you might want to enhance the weight of bias reduce loss ( loss_br ) to force average grid to be a uniform grid in [-1 ,1] 

Please note that previously there was a bug (now fixed) in function getBaseGrid().

**Comment by o0t1ng0o** [comment]
I download the latest code and train the model with 64x64 size image on CelebA dataset.
Then, I met this error.
`Traceback (most recent call last):
  File "train_InstinsicDAE_CelebA.py", line 252, in <module>
    dp0_S, dp0_T, dp0_I, dp0_W, dp0_output, dp0_Wact = decoders(dp0_zS, dp0_zT, dp0_zW, baseg)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/valentina/DeformingAutoencoders-pytorch-latest/DAENet_InstanceNorm.py", line 566, in forward
    self.shading = self.decoderS(zS.view(-1,self.sdim,1,1))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/valentina/DeformingAutoencoders-pytorch-latest/DAENet_InstanceNorm.py", line 391, in forward
    return self.main(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/instancenorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1305, in instance_norm
    eps=eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 68, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1293, in _instance_norm
    training=use_input_stats, momentum=momentum, eps=eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1251, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size [1, 1600, 1, 1]
`
Is there any problem while using instance norm?

**Comment by o0t1ng0o** [comment]
I found that the equation of instance normalization is as follows:
![instancenorm](https://user-images.githubusercontent.com/16815652/49416962-e2718880-f7b6-11e8-8274-a0017b348ee5.png)
When the size of image is 1x1,  x−E[x] = 0.
So the input of `self.decoderS( )` should not be 100x16x1x1?

**Comment by zhixinshu** [comment]
Just fixed the issue in DenseNet architecture with InstanceNorm, now both --useDense=True and --useDense=False should work with InstanceNorm.

**Comment by o0t1ng0o** [comment]
I saw it. 
I found that the reason why the texture had been placed in the left upper corner is that i didn't split the training set into several parts.
After doing this, the texture will stay in the center of the image.

In addition, i want to know why you replace batch normalization with instance normalization instead of fixing the bias of batch normalization while testing?

**Comment by o0t1ng0o** [comment]
Hi, @zhixinshu.
I met another problem.
When i use the pretrained model your provided to produce the texture, the texture seems to be well-aligned.
However, when i train the model with 128x128 input, the texture it produces is not well-aligned and diverse.
The input images, texture images and the output images are as follows.

For the model with 64x64 size input:
1.The input image
![img0_1](https://user-images.githubusercontent.com/16815652/49920067-d76bd600-fee3-11e8-839a-37e95389556e.jpg)
2.The texture image
![tex0_1](https://user-images.githubusercontent.com/16815652/49920074-ddfa4d80-fee3-11e8-9b23-9929d5989504.jpg)
3.The output image
![output0_1](https://user-images.githubusercontent.com/16815652/49920077-e5b9f200-fee3-11e8-8e6d-c91bed5edd54.jpg)

For the model with 128x128 size input:
1.The input image
![img0_1 2](https://user-images.githubusercontent.com/16815652/49920104-f79b9500-fee3-11e8-9496-ad29fc77b6d5.jpg)
2.The texture image
![tex0_1 2](https://user-images.githubusercontent.com/16815652/49920112-fbc7b280-fee3-11e8-8ccd-fbb911bdf1b0.jpg)
3.The output image
![output0_1 2](https://user-images.githubusercontent.com/16815652/49920117-0124fd00-fee4-11e8-9950-087a522616dc.jpg)

Should i decrease the weight of loss_tvw? But, i found it useless for this problem.
Could you give me some advice? Many thanks!

**Comment by zhixinshu** [comment]
What are the length (dimensionality) of the latent codes for the experiments with 64x64 and 128x128 respectively? It seems the texture learned here in 128x128 images contain significant variability of shape deformation. In practice better alignment could be achieved by shorten the latent code of texture while enlarge or maintain the capacity for deformation to push more variability to the deformation branch.

**Comment by o0t1ng0o** [comment]
I use the default settings from the code repository while training 128x128.
The texture is composed of shading and albedo. 
So i only need to shorten the latent codes of them?
Like opt.sdim = 8, opt.tdim = 8?
